# This is a basic workflow that is manually triggered

name: Regenerate HTML

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ build-master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: peppa-runner

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v2
      name: 'Checkout'
    - name: Install dependencies
      run: |
        git rm -r words
        mkdir words
        chmod +x ./regenerate_html.sh
        ./regenerate_html.sh
        git add words
        git add index.html sitemap.xml
        git push -f origin build-master
