# This is a basic workflow that is manually triggered

name: Regenerate HTML

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ build-master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      env:
        SSH_PUBKEY: ${{ secrets.SSH_KEY_PUB  }}
        SSH_PRIVATEKEY: ${{ secrets.SSH_KEY_RSA }}
      run: |
        git config pull.rebase false
        git config user.name "p1ratrulezzz"
        git config user.email "git@p1ratrulezzz.me"
        KEY_PATH=$(pwd -P)"/deployment-private.key"
        KEY_PATH_PUB=$(pwd -P)"/deployment-public.key"
        echo "${SSH_PUBKEY}" > "${KEY_PATH_PUB}"
        echo "Adding an SSH key to agent"
        eval $(ssh-agent -s)
        touch "${KEY_PATH}"
        chmod 0600 "${KEY_PATH}"
        echo "${SSH_PRIVATEKEY}" > "${KEY_PATH}"
        ssh-add -t 3600 "${KEY_PATH}"
        sudo apt install -y python3-venv git
        echo "Checkout master"
        git fetch origin
        git checkout -b master origin/master
        git pull origin master
        echo "Deleting words dir"
        git rm -r words
        mkdir words
        echo "Renegerating..."
        chmod +x ./regenerate_html.sh
        ./regenerate_html.sh
        echo "Add to git"
        git add words
        git add index.html sitemap.xml
        git commit -m"Words CI update"
        git push -f origin master
        rm "${KEY_PATH_PUB}
        rm "${KEY_PATH_PUB}"
