# This is a basic workflow that is manually triggered

name: Regenerate HTML

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      env:
        SSH_PUBKEY: ${{ secrets.SSH_KEY_PUB  }}
        SSH_PRIVATEKEY: ${{ secrets.SSH_KEY_RSA }}
      run: |
        chmod +x ci-build.sh
        ./ci-build.sh
